apiVersion: v1
kind: Service
metadata:
  labels:
    app: exp-test-demo
  name: exp-test-service
spec:
  ports:
  - name: exp-test-port
    port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: exp-test-demo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: exp-test-demo
  name: exp-test-statefulset
spec:
  serviceName: exp-test-service  # <-- Add this line
  replicas: 1
  selector:
    matchLabels:
      app: exp-test-demo
  template:
    metadata:
      labels:
        app: exp-test-demo
    spec:
      containers:
      - image: joshuaissb/exp_test:latest
        name: exp-test-container
        ports:
        - containerPort: 8085
        volumeMounts:
        - mountPath: /data
          name: my-volume
      volumes: 
      - name: my-volume
        persistentVolumeClaim:
          claimName: my-pvc
