apiVersion: v1
kind: Service
metadata:
  labels:
    app: exp-test-demo1
  name: exp-test-service1
spec:
  ports:
  - name: exp-test-port1
    port: 8085
    protocol: TCP
    targetPort: 8085
  selector:
    app: exp-test-demo1

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: exp-test-demo1
  name: exp-test-statefulset1
spec:
  serviceName: exp-test-service1
  replicas: 1
  selector:
    matchLabels:
      app: exp-test-demo1
  template:
    metadata:
      labels:
        app: exp-test-demo1
    spec:
      containers:
      - image: joshuaissb/exp_test_pi:latest
        name: exp-test-container
        ports:
        - containerPort: 8085

