apiVersion: custompodautoscaler.com/v1
kind: CustomPodAutoscaler
metadata:
  name: ppa
  labels: 
    app: cpuint
    tier: cloud
    role: cpa
spec:
  template:
    spec:
      containers:
      - name: python-custom-autoscaler
        image: joshuaissb/python-cpa:latest
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: exp-test-statefulset
  config:
    - name: interval
      value: "20000" # milliseconds
    - name: minReplicas
      value: "1"
    - name: runMode
      value: "per-resource"
    - name: ScalerLink
      value: "https://github.com/Li-Ju666/CustomModels/raw/master/keras/scaler"
    - name: ModelLink
      value: "https://github.com/Li-Ju666/CustomModels/raw/master/keras/model"
    - name: ModelType
      value: "keras"
    - name: Threshold
      value: "0.85"